### ISSUE TITLE
plz remove this mod 

### ISSUE THREAD

**Issue by loordgek** [viniciuslrangel/Sigma#5]
can you plz remove this mod

https://twitter.com/Vazkii/status/703592561777221632

and

https://twitter.com/Vazkii/status/703592725489328128

**Comment by viniciuslrangel** [comment]
I'm confused... I'll stop update curse for now, and in the next version of PSI probably won't work more.
I wanted to make a mod like Lego Mindstorms and I saw the PSI and think to make a addon for it, if a publish a mod so similar now, I'll fells bad.
